kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.configMapName }}
  namespace: sju
data:
{{- if .Values.configFiles }}
  nginx.conf: |-
{{ .Files.Get "files/nginx-config" | indent 4 }}
{{ end }}

